#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatchNightTool
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SUSDB")]
	public partial class WSUSDatabaseClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttbComputerTarget(tbComputerTarget instance);
    partial void UpdatetbComputerTarget(tbComputerTarget instance);
    partial void DeletetbComputerTarget(tbComputerTarget instance);
    partial void InserttbComputerTargetDetail(tbComputerTargetDetail instance);
    partial void UpdatetbComputerTargetDetail(tbComputerTargetDetail instance);
    partial void DeletetbComputerTargetDetail(tbComputerTargetDetail instance);
    partial void InserttbComputerSummaryForMicrosoftUpdate(tbComputerSummaryForMicrosoftUpdate instance);
    partial void UpdatetbComputerSummaryForMicrosoftUpdate(tbComputerSummaryForMicrosoftUpdate instance);
    partial void DeletetbComputerSummaryForMicrosoftUpdate(tbComputerSummaryForMicrosoftUpdate instance);
    #endregion
		
		public WSUSDatabaseClassesDataContext() : 
				base(global::PatchNightTool.Properties.Settings.Default.SUSDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public WSUSDatabaseClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WSUSDatabaseClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WSUSDatabaseClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WSUSDatabaseClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbComputerTarget> tbComputerTargets
		{
			get
			{
				return this.GetTable<tbComputerTarget>();
			}
		}
		
		public System.Data.Linq.Table<tbComputerTargetDetail> tbComputerTargetDetails
		{
			get
			{
				return this.GetTable<tbComputerTargetDetail>();
			}
		}
		
		public System.Data.Linq.Table<tbComputerSummaryForMicrosoftUpdate> tbComputerSummaryForMicrosoftUpdates
		{
			get
			{
				return this.GetTable<tbComputerSummaryForMicrosoftUpdate>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbComputerTarget")]
	public partial class tbComputerTarget : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TargetID;
		
		private string _ComputerID;
		
		private System.Data.Linq.Binary _SID;
		
		private System.Nullable<System.DateTime> _LastSyncTime;
		
		private System.Nullable<System.DateTime> _LastReportedStatusTime;
		
		private System.Nullable<System.DateTime> _LastReportedRebootTime;
		
		private string _IPAddress;
		
		private string _FullDomainName;
		
		private bool _IsRegistered;
		
		private System.Nullable<System.DateTime> _LastInventoryTime;
		
		private System.Nullable<System.DateTime> _LastNameChangeTime;
		
		private System.Nullable<System.DateTime> _EffectiveLastDetectionTime;
		
		private System.Nullable<int> _ParentServerTargetID;
		
		private int _LastSyncResult;
		
		private EntityRef<tbComputerSummaryForMicrosoftUpdate> _tbComputerSummaryForMicrosoftUpdate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTargetIDChanging(int value);
    partial void OnTargetIDChanged();
    partial void OnComputerIDChanging(string value);
    partial void OnComputerIDChanged();
    partial void OnSIDChanging(System.Data.Linq.Binary value);
    partial void OnSIDChanged();
    partial void OnLastSyncTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnLastSyncTimeChanged();
    partial void OnLastReportedStatusTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnLastReportedStatusTimeChanged();
    partial void OnLastReportedRebootTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnLastReportedRebootTimeChanged();
    partial void OnIPAddressChanging(string value);
    partial void OnIPAddressChanged();
    partial void OnFullDomainNameChanging(string value);
    partial void OnFullDomainNameChanged();
    partial void OnIsRegisteredChanging(bool value);
    partial void OnIsRegisteredChanged();
    partial void OnLastInventoryTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnLastInventoryTimeChanged();
    partial void OnLastNameChangeTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnLastNameChangeTimeChanged();
    partial void OnEffectiveLastDetectionTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnEffectiveLastDetectionTimeChanged();
    partial void OnParentServerTargetIDChanging(System.Nullable<int> value);
    partial void OnParentServerTargetIDChanged();
    partial void OnLastSyncResultChanging(int value);
    partial void OnLastSyncResultChanged();
    #endregion
		
		public tbComputerTarget()
		{
			this._tbComputerSummaryForMicrosoftUpdate = default(EntityRef<tbComputerSummaryForMicrosoftUpdate>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TargetID
		{
			get
			{
				return this._TargetID;
			}
			set
			{
				if ((this._TargetID != value))
				{
					this.OnTargetIDChanging(value);
					this.SendPropertyChanging();
					this._TargetID = value;
					this.SendPropertyChanged("TargetID");
					this.OnTargetIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComputerID", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string ComputerID
		{
			get
			{
				return this._ComputerID;
			}
			set
			{
				if ((this._ComputerID != value))
				{
					this.OnComputerIDChanging(value);
					this.SendPropertyChanging();
					this._ComputerID = value;
					this.SendPropertyChanged("ComputerID");
					this.OnComputerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", DbType="VarBinary(85)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary SID
		{
			get
			{
				return this._SID;
			}
			set
			{
				if ((this._SID != value))
				{
					this.OnSIDChanging(value);
					this.SendPropertyChanging();
					this._SID = value;
					this.SendPropertyChanged("SID");
					this.OnSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastSyncTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastSyncTime
		{
			get
			{
				return this._LastSyncTime;
			}
			set
			{
				if ((this._LastSyncTime != value))
				{
					this.OnLastSyncTimeChanging(value);
					this.SendPropertyChanging();
					this._LastSyncTime = value;
					this.SendPropertyChanged("LastSyncTime");
					this.OnLastSyncTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastReportedStatusTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastReportedStatusTime
		{
			get
			{
				return this._LastReportedStatusTime;
			}
			set
			{
				if ((this._LastReportedStatusTime != value))
				{
					this.OnLastReportedStatusTimeChanging(value);
					this.SendPropertyChanging();
					this._LastReportedStatusTime = value;
					this.SendPropertyChanged("LastReportedStatusTime");
					this.OnLastReportedStatusTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastReportedRebootTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastReportedRebootTime
		{
			get
			{
				return this._LastReportedRebootTime;
			}
			set
			{
				if ((this._LastReportedRebootTime != value))
				{
					this.OnLastReportedRebootTimeChanging(value);
					this.SendPropertyChanging();
					this._LastReportedRebootTime = value;
					this.SendPropertyChanged("LastReportedRebootTime");
					this.OnLastReportedRebootTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPAddress", DbType="NVarChar(56)")]
		public string IPAddress
		{
			get
			{
				return this._IPAddress;
			}
			set
			{
				if ((this._IPAddress != value))
				{
					this.OnIPAddressChanging(value);
					this.SendPropertyChanging();
					this._IPAddress = value;
					this.SendPropertyChanged("IPAddress");
					this.OnIPAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullDomainName", DbType="NVarChar(255)")]
		public string FullDomainName
		{
			get
			{
				return this._FullDomainName;
			}
			set
			{
				if ((this._FullDomainName != value))
				{
					this.OnFullDomainNameChanging(value);
					this.SendPropertyChanging();
					this._FullDomainName = value;
					this.SendPropertyChanged("FullDomainName");
					this.OnFullDomainNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRegistered", DbType="Bit NOT NULL")]
		public bool IsRegistered
		{
			get
			{
				return this._IsRegistered;
			}
			set
			{
				if ((this._IsRegistered != value))
				{
					this.OnIsRegisteredChanging(value);
					this.SendPropertyChanging();
					this._IsRegistered = value;
					this.SendPropertyChanged("IsRegistered");
					this.OnIsRegisteredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastInventoryTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastInventoryTime
		{
			get
			{
				return this._LastInventoryTime;
			}
			set
			{
				if ((this._LastInventoryTime != value))
				{
					this.OnLastInventoryTimeChanging(value);
					this.SendPropertyChanging();
					this._LastInventoryTime = value;
					this.SendPropertyChanged("LastInventoryTime");
					this.OnLastInventoryTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastNameChangeTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastNameChangeTime
		{
			get
			{
				return this._LastNameChangeTime;
			}
			set
			{
				if ((this._LastNameChangeTime != value))
				{
					this.OnLastNameChangeTimeChanging(value);
					this.SendPropertyChanging();
					this._LastNameChangeTime = value;
					this.SendPropertyChanged("LastNameChangeTime");
					this.OnLastNameChangeTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EffectiveLastDetectionTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> EffectiveLastDetectionTime
		{
			get
			{
				return this._EffectiveLastDetectionTime;
			}
			set
			{
				if ((this._EffectiveLastDetectionTime != value))
				{
					this.OnEffectiveLastDetectionTimeChanging(value);
					this.SendPropertyChanging();
					this._EffectiveLastDetectionTime = value;
					this.SendPropertyChanged("EffectiveLastDetectionTime");
					this.OnEffectiveLastDetectionTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentServerTargetID", DbType="Int")]
		public System.Nullable<int> ParentServerTargetID
		{
			get
			{
				return this._ParentServerTargetID;
			}
			set
			{
				if ((this._ParentServerTargetID != value))
				{
					this.OnParentServerTargetIDChanging(value);
					this.SendPropertyChanging();
					this._ParentServerTargetID = value;
					this.SendPropertyChanged("ParentServerTargetID");
					this.OnParentServerTargetIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastSyncResult", DbType="Int NOT NULL")]
		public int LastSyncResult
		{
			get
			{
				return this._LastSyncResult;
			}
			set
			{
				if ((this._LastSyncResult != value))
				{
					this.OnLastSyncResultChanging(value);
					this.SendPropertyChanging();
					this._LastSyncResult = value;
					this.SendPropertyChanged("LastSyncResult");
					this.OnLastSyncResultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbComputerTarget_tbComputerSummaryForMicrosoftUpdate", Storage="_tbComputerSummaryForMicrosoftUpdate", ThisKey="TargetID", OtherKey="TargetID", IsUnique=true, IsForeignKey=false)]
		public tbComputerSummaryForMicrosoftUpdate tbComputerSummaryForMicrosoftUpdate
		{
			get
			{
				return this._tbComputerSummaryForMicrosoftUpdate.Entity;
			}
			set
			{
				tbComputerSummaryForMicrosoftUpdate previousValue = this._tbComputerSummaryForMicrosoftUpdate.Entity;
				if (((previousValue != value) 
							|| (this._tbComputerSummaryForMicrosoftUpdate.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbComputerSummaryForMicrosoftUpdate.Entity = null;
						previousValue.tbComputerTarget = null;
					}
					this._tbComputerSummaryForMicrosoftUpdate.Entity = value;
					if ((value != null))
					{
						value.tbComputerTarget = this;
					}
					this.SendPropertyChanged("tbComputerSummaryForMicrosoftUpdate");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbComputerTargetDetail")]
	public partial class tbComputerTargetDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TargetID;
		
		private System.Nullable<int> _OSMajorVersion;
		
		private System.Nullable<int> _OSMinorVersion;
		
		private System.Nullable<int> _OSBuildNumber;
		
		private System.Nullable<int> _OSServicePackMajorNumber;
		
		private System.Nullable<int> _OSServicePackMinorNumber;
		
		private string _OSLocale;
		
		private string _ComputerMake;
		
		private string _ComputerModel;
		
		private string _BiosVersion;
		
		private string _BiosName;
		
		private System.Nullable<System.DateTime> _BiosReleaseDate;
		
		private string _ProcessorArchitecture;
		
		private System.Nullable<System.DateTime> _LastStatusRollupTime;
		
		private int _LastReceivedStatusRollupNumber;
		
		private int _LastSentStatusRollupNumber;
		
		private int _SamplingValue;
		
		private System.DateTime _CreatedTime;
		
		private short _SuiteMask;
		
		private byte _OldProductType;
		
		private int _NewProductType;
		
		private int _SystemMetrics;
		
		private string _ClientVersion;
		
		private bool _TargetGroupMembershipChanged;
		
		private string _OSFamily;
		
		private string _OSDescription;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTargetIDChanging(int value);
    partial void OnTargetIDChanged();
    partial void OnOSMajorVersionChanging(System.Nullable<int> value);
    partial void OnOSMajorVersionChanged();
    partial void OnOSMinorVersionChanging(System.Nullable<int> value);
    partial void OnOSMinorVersionChanged();
    partial void OnOSBuildNumberChanging(System.Nullable<int> value);
    partial void OnOSBuildNumberChanged();
    partial void OnOSServicePackMajorNumberChanging(System.Nullable<int> value);
    partial void OnOSServicePackMajorNumberChanged();
    partial void OnOSServicePackMinorNumberChanging(System.Nullable<int> value);
    partial void OnOSServicePackMinorNumberChanged();
    partial void OnOSLocaleChanging(string value);
    partial void OnOSLocaleChanged();
    partial void OnComputerMakeChanging(string value);
    partial void OnComputerMakeChanged();
    partial void OnComputerModelChanging(string value);
    partial void OnComputerModelChanged();
    partial void OnBiosVersionChanging(string value);
    partial void OnBiosVersionChanged();
    partial void OnBiosNameChanging(string value);
    partial void OnBiosNameChanged();
    partial void OnBiosReleaseDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBiosReleaseDateChanged();
    partial void OnProcessorArchitectureChanging(string value);
    partial void OnProcessorArchitectureChanged();
    partial void OnLastStatusRollupTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnLastStatusRollupTimeChanged();
    partial void OnLastReceivedStatusRollupNumberChanging(int value);
    partial void OnLastReceivedStatusRollupNumberChanged();
    partial void OnLastSentStatusRollupNumberChanging(int value);
    partial void OnLastSentStatusRollupNumberChanged();
    partial void OnSamplingValueChanging(int value);
    partial void OnSamplingValueChanged();
    partial void OnCreatedTimeChanging(System.DateTime value);
    partial void OnCreatedTimeChanged();
    partial void OnSuiteMaskChanging(short value);
    partial void OnSuiteMaskChanged();
    partial void OnOldProductTypeChanging(byte value);
    partial void OnOldProductTypeChanged();
    partial void OnNewProductTypeChanging(int value);
    partial void OnNewProductTypeChanged();
    partial void OnSystemMetricsChanging(int value);
    partial void OnSystemMetricsChanged();
    partial void OnClientVersionChanging(string value);
    partial void OnClientVersionChanged();
    partial void OnTargetGroupMembershipChangedChanging(bool value);
    partial void OnTargetGroupMembershipChangedChanged();
    partial void OnOSFamilyChanging(string value);
    partial void OnOSFamilyChanged();
    partial void OnOSDescriptionChanging(string value);
    partial void OnOSDescriptionChanged();
    #endregion
		
		public tbComputerTargetDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TargetID
		{
			get
			{
				return this._TargetID;
			}
			set
			{
				if ((this._TargetID != value))
				{
					this.OnTargetIDChanging(value);
					this.SendPropertyChanging();
					this._TargetID = value;
					this.SendPropertyChanged("TargetID");
					this.OnTargetIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSMajorVersion", DbType="Int")]
		public System.Nullable<int> OSMajorVersion
		{
			get
			{
				return this._OSMajorVersion;
			}
			set
			{
				if ((this._OSMajorVersion != value))
				{
					this.OnOSMajorVersionChanging(value);
					this.SendPropertyChanging();
					this._OSMajorVersion = value;
					this.SendPropertyChanged("OSMajorVersion");
					this.OnOSMajorVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSMinorVersion", DbType="Int")]
		public System.Nullable<int> OSMinorVersion
		{
			get
			{
				return this._OSMinorVersion;
			}
			set
			{
				if ((this._OSMinorVersion != value))
				{
					this.OnOSMinorVersionChanging(value);
					this.SendPropertyChanging();
					this._OSMinorVersion = value;
					this.SendPropertyChanged("OSMinorVersion");
					this.OnOSMinorVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSBuildNumber", DbType="Int")]
		public System.Nullable<int> OSBuildNumber
		{
			get
			{
				return this._OSBuildNumber;
			}
			set
			{
				if ((this._OSBuildNumber != value))
				{
					this.OnOSBuildNumberChanging(value);
					this.SendPropertyChanging();
					this._OSBuildNumber = value;
					this.SendPropertyChanged("OSBuildNumber");
					this.OnOSBuildNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSServicePackMajorNumber", DbType="Int")]
		public System.Nullable<int> OSServicePackMajorNumber
		{
			get
			{
				return this._OSServicePackMajorNumber;
			}
			set
			{
				if ((this._OSServicePackMajorNumber != value))
				{
					this.OnOSServicePackMajorNumberChanging(value);
					this.SendPropertyChanging();
					this._OSServicePackMajorNumber = value;
					this.SendPropertyChanged("OSServicePackMajorNumber");
					this.OnOSServicePackMajorNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSServicePackMinorNumber", DbType="Int")]
		public System.Nullable<int> OSServicePackMinorNumber
		{
			get
			{
				return this._OSServicePackMinorNumber;
			}
			set
			{
				if ((this._OSServicePackMinorNumber != value))
				{
					this.OnOSServicePackMinorNumberChanging(value);
					this.SendPropertyChanging();
					this._OSServicePackMinorNumber = value;
					this.SendPropertyChanged("OSServicePackMinorNumber");
					this.OnOSServicePackMinorNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSLocale", DbType="NVarChar(10)")]
		public string OSLocale
		{
			get
			{
				return this._OSLocale;
			}
			set
			{
				if ((this._OSLocale != value))
				{
					this.OnOSLocaleChanging(value);
					this.SendPropertyChanging();
					this._OSLocale = value;
					this.SendPropertyChanged("OSLocale");
					this.OnOSLocaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComputerMake", DbType="NVarChar(64)")]
		public string ComputerMake
		{
			get
			{
				return this._ComputerMake;
			}
			set
			{
				if ((this._ComputerMake != value))
				{
					this.OnComputerMakeChanging(value);
					this.SendPropertyChanging();
					this._ComputerMake = value;
					this.SendPropertyChanged("ComputerMake");
					this.OnComputerMakeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComputerModel", DbType="NVarChar(64)")]
		public string ComputerModel
		{
			get
			{
				return this._ComputerModel;
			}
			set
			{
				if ((this._ComputerModel != value))
				{
					this.OnComputerModelChanging(value);
					this.SendPropertyChanging();
					this._ComputerModel = value;
					this.SendPropertyChanged("ComputerModel");
					this.OnComputerModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BiosVersion", DbType="NVarChar(64)")]
		public string BiosVersion
		{
			get
			{
				return this._BiosVersion;
			}
			set
			{
				if ((this._BiosVersion != value))
				{
					this.OnBiosVersionChanging(value);
					this.SendPropertyChanging();
					this._BiosVersion = value;
					this.SendPropertyChanged("BiosVersion");
					this.OnBiosVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BiosName", DbType="NVarChar(64)")]
		public string BiosName
		{
			get
			{
				return this._BiosName;
			}
			set
			{
				if ((this._BiosName != value))
				{
					this.OnBiosNameChanging(value);
					this.SendPropertyChanging();
					this._BiosName = value;
					this.SendPropertyChanged("BiosName");
					this.OnBiosNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BiosReleaseDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> BiosReleaseDate
		{
			get
			{
				return this._BiosReleaseDate;
			}
			set
			{
				if ((this._BiosReleaseDate != value))
				{
					this.OnBiosReleaseDateChanging(value);
					this.SendPropertyChanging();
					this._BiosReleaseDate = value;
					this.SendPropertyChanged("BiosReleaseDate");
					this.OnBiosReleaseDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcessorArchitecture", DbType="NVarChar(50)")]
		public string ProcessorArchitecture
		{
			get
			{
				return this._ProcessorArchitecture;
			}
			set
			{
				if ((this._ProcessorArchitecture != value))
				{
					this.OnProcessorArchitectureChanging(value);
					this.SendPropertyChanging();
					this._ProcessorArchitecture = value;
					this.SendPropertyChanged("ProcessorArchitecture");
					this.OnProcessorArchitectureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastStatusRollupTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastStatusRollupTime
		{
			get
			{
				return this._LastStatusRollupTime;
			}
			set
			{
				if ((this._LastStatusRollupTime != value))
				{
					this.OnLastStatusRollupTimeChanging(value);
					this.SendPropertyChanging();
					this._LastStatusRollupTime = value;
					this.SendPropertyChanged("LastStatusRollupTime");
					this.OnLastStatusRollupTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastReceivedStatusRollupNumber", DbType="Int NOT NULL")]
		public int LastReceivedStatusRollupNumber
		{
			get
			{
				return this._LastReceivedStatusRollupNumber;
			}
			set
			{
				if ((this._LastReceivedStatusRollupNumber != value))
				{
					this.OnLastReceivedStatusRollupNumberChanging(value);
					this.SendPropertyChanging();
					this._LastReceivedStatusRollupNumber = value;
					this.SendPropertyChanged("LastReceivedStatusRollupNumber");
					this.OnLastReceivedStatusRollupNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastSentStatusRollupNumber", DbType="Int NOT NULL")]
		public int LastSentStatusRollupNumber
		{
			get
			{
				return this._LastSentStatusRollupNumber;
			}
			set
			{
				if ((this._LastSentStatusRollupNumber != value))
				{
					this.OnLastSentStatusRollupNumberChanging(value);
					this.SendPropertyChanging();
					this._LastSentStatusRollupNumber = value;
					this.SendPropertyChanged("LastSentStatusRollupNumber");
					this.OnLastSentStatusRollupNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SamplingValue", DbType="Int NOT NULL")]
		public int SamplingValue
		{
			get
			{
				return this._SamplingValue;
			}
			set
			{
				if ((this._SamplingValue != value))
				{
					this.OnSamplingValueChanging(value);
					this.SendPropertyChanging();
					this._SamplingValue = value;
					this.SendPropertyChanged("SamplingValue");
					this.OnSamplingValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedTime", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedTime
		{
			get
			{
				return this._CreatedTime;
			}
			set
			{
				if ((this._CreatedTime != value))
				{
					this.OnCreatedTimeChanging(value);
					this.SendPropertyChanging();
					this._CreatedTime = value;
					this.SendPropertyChanged("CreatedTime");
					this.OnCreatedTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SuiteMask", DbType="SmallInt NOT NULL")]
		public short SuiteMask
		{
			get
			{
				return this._SuiteMask;
			}
			set
			{
				if ((this._SuiteMask != value))
				{
					this.OnSuiteMaskChanging(value);
					this.SendPropertyChanging();
					this._SuiteMask = value;
					this.SendPropertyChanged("SuiteMask");
					this.OnSuiteMaskChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OldProductType", DbType="TinyInt NOT NULL")]
		public byte OldProductType
		{
			get
			{
				return this._OldProductType;
			}
			set
			{
				if ((this._OldProductType != value))
				{
					this.OnOldProductTypeChanging(value);
					this.SendPropertyChanging();
					this._OldProductType = value;
					this.SendPropertyChanged("OldProductType");
					this.OnOldProductTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewProductType", DbType="Int NOT NULL")]
		public int NewProductType
		{
			get
			{
				return this._NewProductType;
			}
			set
			{
				if ((this._NewProductType != value))
				{
					this.OnNewProductTypeChanging(value);
					this.SendPropertyChanging();
					this._NewProductType = value;
					this.SendPropertyChanged("NewProductType");
					this.OnNewProductTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemMetrics", DbType="Int NOT NULL")]
		public int SystemMetrics
		{
			get
			{
				return this._SystemMetrics;
			}
			set
			{
				if ((this._SystemMetrics != value))
				{
					this.OnSystemMetricsChanging(value);
					this.SendPropertyChanging();
					this._SystemMetrics = value;
					this.SendPropertyChanged("SystemMetrics");
					this.OnSystemMetricsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientVersion", DbType="NVarChar(23)")]
		public string ClientVersion
		{
			get
			{
				return this._ClientVersion;
			}
			set
			{
				if ((this._ClientVersion != value))
				{
					this.OnClientVersionChanging(value);
					this.SendPropertyChanging();
					this._ClientVersion = value;
					this.SendPropertyChanged("ClientVersion");
					this.OnClientVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetGroupMembershipChanged", DbType="Bit NOT NULL")]
		public bool TargetGroupMembershipChanged
		{
			get
			{
				return this._TargetGroupMembershipChanged;
			}
			set
			{
				if ((this._TargetGroupMembershipChanged != value))
				{
					this.OnTargetGroupMembershipChangedChanging(value);
					this.SendPropertyChanging();
					this._TargetGroupMembershipChanged = value;
					this.SendPropertyChanged("TargetGroupMembershipChanged");
					this.OnTargetGroupMembershipChangedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSFamily", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string OSFamily
		{
			get
			{
				return this._OSFamily;
			}
			set
			{
				if ((this._OSFamily != value))
				{
					this.OnOSFamilyChanging(value);
					this.SendPropertyChanging();
					this._OSFamily = value;
					this.SendPropertyChanged("OSFamily");
					this.OnOSFamilyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSDescription", DbType="NVarChar(256)")]
		public string OSDescription
		{
			get
			{
				return this._OSDescription;
			}
			set
			{
				if ((this._OSDescription != value))
				{
					this.OnOSDescriptionChanging(value);
					this.SendPropertyChanging();
					this._OSDescription = value;
					this.SendPropertyChanged("OSDescription");
					this.OnOSDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbComputerSummaryForMicrosoftUpdates")]
	public partial class tbComputerSummaryForMicrosoftUpdate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TargetID;
		
		private int _Unknown;
		
		private int _NotInstalled;
		
		private int _Downloaded;
		
		private int _Installed;
		
		private int _Failed;
		
		private int _InstalledPendingReboot;
		
		private System.DateTime _LastChangeTime;
		
		private EntityRef<tbComputerTarget> _tbComputerTarget;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTargetIDChanging(int value);
    partial void OnTargetIDChanged();
    partial void OnUnknownChanging(int value);
    partial void OnUnknownChanged();
    partial void OnNotInstalledChanging(int value);
    partial void OnNotInstalledChanged();
    partial void OnDownloadedChanging(int value);
    partial void OnDownloadedChanged();
    partial void OnInstalledChanging(int value);
    partial void OnInstalledChanged();
    partial void OnFailedChanging(int value);
    partial void OnFailedChanged();
    partial void OnInstalledPendingRebootChanging(int value);
    partial void OnInstalledPendingRebootChanged();
    partial void OnLastChangeTimeChanging(System.DateTime value);
    partial void OnLastChangeTimeChanged();
    #endregion
		
		public tbComputerSummaryForMicrosoftUpdate()
		{
			this._tbComputerTarget = default(EntityRef<tbComputerTarget>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TargetID
		{
			get
			{
				return this._TargetID;
			}
			set
			{
				if ((this._TargetID != value))
				{
					if (this._tbComputerTarget.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTargetIDChanging(value);
					this.SendPropertyChanging();
					this._TargetID = value;
					this.SendPropertyChanged("TargetID");
					this.OnTargetIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unknown", DbType="Int NOT NULL")]
		public int Unknown
		{
			get
			{
				return this._Unknown;
			}
			set
			{
				if ((this._Unknown != value))
				{
					this.OnUnknownChanging(value);
					this.SendPropertyChanging();
					this._Unknown = value;
					this.SendPropertyChanged("Unknown");
					this.OnUnknownChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotInstalled", DbType="Int NOT NULL")]
		public int NotInstalled
		{
			get
			{
				return this._NotInstalled;
			}
			set
			{
				if ((this._NotInstalled != value))
				{
					this.OnNotInstalledChanging(value);
					this.SendPropertyChanging();
					this._NotInstalled = value;
					this.SendPropertyChanged("NotInstalled");
					this.OnNotInstalledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Downloaded", DbType="Int NOT NULL")]
		public int Downloaded
		{
			get
			{
				return this._Downloaded;
			}
			set
			{
				if ((this._Downloaded != value))
				{
					this.OnDownloadedChanging(value);
					this.SendPropertyChanging();
					this._Downloaded = value;
					this.SendPropertyChanged("Downloaded");
					this.OnDownloadedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Installed", DbType="Int NOT NULL")]
		public int Installed
		{
			get
			{
				return this._Installed;
			}
			set
			{
				if ((this._Installed != value))
				{
					this.OnInstalledChanging(value);
					this.SendPropertyChanging();
					this._Installed = value;
					this.SendPropertyChanged("Installed");
					this.OnInstalledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Failed", DbType="Int NOT NULL")]
		public int Failed
		{
			get
			{
				return this._Failed;
			}
			set
			{
				if ((this._Failed != value))
				{
					this.OnFailedChanging(value);
					this.SendPropertyChanging();
					this._Failed = value;
					this.SendPropertyChanged("Failed");
					this.OnFailedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstalledPendingReboot", DbType="Int NOT NULL")]
		public int InstalledPendingReboot
		{
			get
			{
				return this._InstalledPendingReboot;
			}
			set
			{
				if ((this._InstalledPendingReboot != value))
				{
					this.OnInstalledPendingRebootChanging(value);
					this.SendPropertyChanging();
					this._InstalledPendingReboot = value;
					this.SendPropertyChanged("InstalledPendingReboot");
					this.OnInstalledPendingRebootChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastChangeTime", DbType="DateTime NOT NULL")]
		public System.DateTime LastChangeTime
		{
			get
			{
				return this._LastChangeTime;
			}
			set
			{
				if ((this._LastChangeTime != value))
				{
					this.OnLastChangeTimeChanging(value);
					this.SendPropertyChanging();
					this._LastChangeTime = value;
					this.SendPropertyChanged("LastChangeTime");
					this.OnLastChangeTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbComputerTarget_tbComputerSummaryForMicrosoftUpdate", Storage="_tbComputerTarget", ThisKey="TargetID", OtherKey="TargetID", IsForeignKey=true)]
		public tbComputerTarget tbComputerTarget
		{
			get
			{
				return this._tbComputerTarget.Entity;
			}
			set
			{
				tbComputerTarget previousValue = this._tbComputerTarget.Entity;
				if (((previousValue != value) 
							|| (this._tbComputerTarget.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbComputerTarget.Entity = null;
						previousValue.tbComputerSummaryForMicrosoftUpdate = null;
					}
					this._tbComputerTarget.Entity = value;
					if ((value != null))
					{
						value.tbComputerSummaryForMicrosoftUpdate = this;
						this._TargetID = value.TargetID;
					}
					else
					{
						this._TargetID = default(int);
					}
					this.SendPropertyChanged("tbComputerTarget");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
